name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  productNamespacePrefix: "ReactiveMvvm"

jobs:
  build:
    uses: reactiveui/actions-common/.github/workflows/workflow-common-setup-and-build.yml@main
    with:
      configuration: Release
      productNamespacePrefix: "ReactiveMvvm"
      useVisualStudioPreview: false
      useMauiCheckDotNetTool: false
      installWindowsSdk: false
      installWorkflows: false
      solutionFile: 'ReactiveMvvm.sln'
